# Generated by Django 5.2.11 on 2026-02-12 20:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('customer_type', models.CharField(choices=[('pf', 'Pessoa Fisica'), ('pj', 'Pessoa Juridica')], max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_group', models.CharField(blank=True, max_length=100, null=True)),
                ('company_segmentation', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'api.customer',
            },
        ),
    ]
