# Generated by Django 5.2.11 on 2026-02-13 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plan_rename_customer_code_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_data', models.DateTimeField()),
                ('source', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('custumer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plan')),
            ],
            options={
                'db_table': 'api.lead',
            },
        ),
    ]
