# Generated by Django 5.2.11 on 2026-02-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customer_unique_active_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_active_email',
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('id',), name='unique_active_id'),
        ),
    ]
