# Generated by Django 5.2.11 on 2026-02-13 16:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_customer_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'api.opportunities',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField()),
                ('start_plan_data', models.DateTimeField()),
                ('end_plan_data', models.DateTimeField()),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_dependents', models.SmallIntegerField()),
                ('observation', models.CharField(max_length=400)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'api.sales',
            },
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='customer_cod',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='custumer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('plan_id',), name='unique_active_plan_id'),
        ),
        migrations.AddField(
            model_name='opportunities',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
        migrations.AddField(
            model_name='opportunities',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lead'),
        ),
        migrations.AddField(
            model_name='opportunities',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plan'),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
        migrations.AddField(
            model_name='sales',
            name='opportunities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.opportunities'),
        ),
        migrations.AddField(
            model_name='sales',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plan'),
        ),
    ]
