# Generated by Django 5.2.11 on 2026-02-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_opportunities_sales_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_active_customer_id',
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('customer_cod',), name='unique_active_customer_cod'),
        ),
    ]
